testing score directly
die-antwort/tischtennisdisplay pull request #1
Opened 2017-04-08 19:28 UTC by calvinclaus

Take a look at this @noniq.

## Things to discuss:

- `Game` spec uses `Score` directly to verify game can undo and delegate to score instead of mocking `Score`. I see no reason to go through the effort to mock `Score`. Do you? 
- `Score` is immutable, nonetheless I decided to keep the test structure like it was in game for now. I wanted to know what you think. Should...
```ruby
 it "knows who won" do
    #after 3*1b -r we are at 10-0 in set 3
    input = %w(l)*12 + %w(r)*12 + %w(l)*10
    score = score(input)
    expect(score.winner).to be_nil
    score = score(input+['l'])
    expect(score.winner).to eq(1)
end
```
...really be:
```ruby
 it "knows if a player won" do
    input = %w(l)*12 + %w(r)*12 + %w(l)*10
    input.push('l')
    score = score(input)
    expect(score.winner).to eq(1)
end
 it "knows if nobody won" do
    input = %w(l)*12 + %w(r)*12 + %w(l)*10
    score = score(input)
    expect(score.winner).to be_nil
end
```
Even though it makes sense to check if `Score` reports a false winner in the same test we are checking if it reports a right winner, the way we are doing it now feels a bit like checking if `add(-1,0)==-1` before checking if `add(1,0)==1` in a single test for add. 
More technically: we are checking two output equivalence classes in a single test. 
I am leaning towards the first solution:
Pros: fewer tests, fewer duplicate lines, it's okay to check two non-invalid equivalence classes in the same test
Cons: a single test can fail for multiple reasons

🔥 🔥 🔥

2017-04-08 22:04 UTC, noniq requested changes
Hm, are you referring to the “max 1 assertion per test” rule here? I’m not a fan of this rule, so I definitely prefer the first variant. From my experience, the “a single test can fail for multiple reasons” case is not a problem in practice, and the first variant is way easier to reason about.

2017-04-08 22:04 UTC, noniq commented on score.rb
> +  WINNING_SET_SCORE = 3
That change should not be part of this commit, I think.

2017-04-08 22:04 UTC, noniq commented on spec/models/game_spec.rb
> +    expect(game.score.p1_score).to eq(3)
Just an idea – maybe these “undo”-tests should look like this:
```ruby
game = game_with_input_sequence(%w(l l r r l))
original_score = game.score
game.handle_input('r')
expect(game.score).to_not eq(original_score)
game.undo
expect(game.score).to eq(original_score)
```

Of course we’d need to implement `Score#==` for this to work.

2017-04-08 22:50 UTC, merged

2017-04-08 22:50 UTC, calvinclaus commented on score.rb
> +  WINNING_SET_SCORE = 3
test fail otherwise

2017-04-09 06:02 UTC, noniq commented on score.rb
> +  WINNING_SET_SCORE = 3
Ah okay, you’re right. But then the commit message should have mentioned why we’re making this (seemingly unrelated) change :)

2017-04-09 06:03 UTC, noniq commented on score.rb
> +    puts "using eq"
The puts seems like a leftover. Should be removed.